#!/bin/sh
SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR_PATH=$(dirname $SCRIPT_PATH)
BASE_DIR=$(dirname $SCRIPT_DIR_PATH)

openssl genrsa -aes256 \
	-out "$BASE_DIR"/intermediate/private/intermediate.key.pem 4096 && \

chmod 400 "$BASE_DIR"/intermediate/private/intermediate.key.pem

