#!/bin/sh
SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR_PATH=$(dirname $SCRIPT_PATH)
BASE_DIR=$(dirname $SCRIPT_DIR_PATH)

DOMAIN=$1
DOMAIN_REVERSE=$(echo $DOMAIN|tr "." "\n"|tac|paste -s -d"."|tr "*" "_")
KEY_PATH="$BASE_DIR"/intermediate/private/$DOMAIN_REVERSE.pem 
OPENSSL_INTERMEDIATE_CONFIG="$BASE_DIR"/intermediate/openssl.conf
OPENSSL_SAN_CONFIG="$BASE_DIR"/intermediate/tmp/openssl.san.$DOMAIN_REVERSE.conf
CSR_PATH="$BASE_DIR"/intermediate/csr/$DOMAIN_REVERSE.csr.pem
CERT_PATH="$BASE_DIR"/intermediate/certs/$DOMAIN_REVERSE.cert.pem

# Create Key
rm -f "$KEY_PATH"
openssl genrsa -out "$KEY_PATH" 2048
chmod 400 "$KEY_PATH"

# Generate OpenSSL config with SAN settings
sed "s/{DOMAIN_NAME}/$DOMAIN/g" "$BASE_DIR"/intermediate/openssl-san.conf.template > "$OPENSSL_SAN_CONFIG"

# Generate CSR
openssl req -config "$OPENSSL_SAN_CONFIG" \
      -key "$KEY_PATH" \
      -new -out "$CSR_PATH"

# Create Certificate
openssl ca -config "$OPENSSL_INTERMEDIATE_CONFIG" \
      -extensions server_cert -days 375 -notext -md sha256 \
      -in "$CSR_PATH" \
      -out "$CERT_PATH" &&
chmod 444 "$CERT_PATH" &&
openssl x509 -noout -text -in "$CERT_PATH"

